### ISSUE TITLE
Add configurable window

### ISSUE THREAD

**Issue by TaniaPash** [piercus/term-annotator#2]
## Actual

configuration for the annotator is stored in **configuration file** : https://github.com/piercus/term-annotator/blob/master/annotator.json

This **annotator.json** config file should be manually updated to set new configuration for the annotator
 
## Proposal

**use **configurable window** to update annotator's config**

### expected application's launching order 
1.  annotator is launched with `npm start`
2. new window with  **configuration** form is opened
3. configuration params are added into form and submitted
4. Annotator is ready for annotation

**Comment by piercus** [comment]
Hello @TaniaPash,

Thank for this issue, i totally agree with you.

2 remarks :
* I suggest we do that step by step, and not trying to put everything in the form at once.
* We should not show this at npm start but more using a menu

So step will be : 
1. move current config to an electron store like https://github.com/sindresorhus/electron-store
2. Add a menu and a "Menu -> Source" option from the menu, open a page that let's you define the source folder
3. Add a menu "Menu -> Categories" option that let you define the output categories


I suggest that "deep confirguration" will have no Menu for now since it's not fully stable.

I would be happy if you can help on (1) and (2)

Thank you

**Comment by TaniaPash** [comment]
done
